name: Deploy to HF Spaces
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
#    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Clone HF Space repo
      run: git clone https://yrajm1997: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@huggingface.co/spaces/yrajm1997/test-02
    
    - name: move inside repo
      run: cd test-02 && echo "FROM yrajm1997/titanic-api:latest" >> Dockerfile && ls
    
    # - name: Set HF Space repo
    #   run: cd test-02 && git remote set-url origin https://yrajm1997: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@huggingface.co/spaces/yrajm1997/test-02
    
    # - name: Delete Dockerfile
    #   run: cd test-02 && if [ -f Dockerfile ] ; then rm Dockerfile ; fi
    
    # - name: Update Dockerfile
    #   run: cd test-02 && echo "FROM yrajm1997/titanic-api:latest" >> Dockerfile
    
    # - name: Push changes
    #   run: cd test-02 && git push --force origin main
