name: Deploy to HF Spaces
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Clone HF Space repo
      run: git clone https://yrajm1997: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@huggingface.co/spaces/yrajm1997/test-02
        
    - name: Set remote origin
      working-directory: ./test-02
      run: git remote set-url origin https://yrajm1997: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@huggingface.co/spaces/yrajm1997/test-02
    
    - name: Update Dockerfile
      working-directory: ./test-02
      run: |
        if grep -q "latest" Dockerfile ; then TEXT="FROM yrajm1997/titanic-api" ; else TEXT="FROM yrajm1997/titanic-api:latest" ; fi
        if [[ -f Dockerfile ]] ; then rm Dockerfile ; fi
        echo "$TEXT" >> Dockerfile
    
    - name: Commit changes
      working-directory: ./test-02
      run: |
        git config --global user.email "yrajm1997@gmail.com"
        git config --global user.name "yrajm1997"
        git add Dockerfile
        git commit -m "dockerfile updated"

    - name: Push changes
      working-directory: ./test-02
      run: git push --force origin main

